-- -------------------------------------------------------------
-- 
-- File Name: D:\Downloads\Research\be\code\codegen\mlhdlc_dwt\hdlsrc\mlhdlc_dwt_fixpt.vhd
-- Created: 2021-11-21 17:24:26
-- 
-- Generated by MATLAB 9.4, MATLAB Coder 4.0 and HDL Coder 3.12
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mlhdlc_dwt_fixpt
-- Source Path: mlhdlc_dwt_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.mlhdlc_dwt_fixpt_pkg.ALL;

ENTITY mlhdlc_dwt_fixpt IS
  PORT( x_in                              :   IN    vector_of_std_logic_vector14(0 TO 7);  -- sfix14_En12 [8]
        y_out                             :   OUT   vector_of_std_logic_vector14(0 TO 7)  -- sfix14_En12 [8]
        );
END mlhdlc_dwt_fixpt;


ARCHITECTURE rtl OF mlhdlc_dwt_fixpt IS

  -- Component Declarations
  COMPONENT dwt
    PORT( x_in                            :   IN    vector_of_std_logic_vector14(0 TO 7);  -- sfix14_En12 [8]
          tmp                             :   OUT   vector_of_std_logic_vector14(0 TO 7)  -- sfix14_En12 [8]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dwt
    USE ENTITY work.dwt(rtl);

  -- Signals
  SIGNAL tmp                              : vector_of_std_logic_vector14(0 TO 7);  -- ufix14 [8]

BEGIN
  -- delayout input signal
  -- 
  -- x_out = idwt(y_out,hid);
  -- 
  -- update the delay line
  -- 
  -- ud8 = ud7; 
  -- 
  -- ud7 = ud6;
  -- 
  -- ud6 = ud5;
  -- 
  -- ud5 = ud4;
  -- 
  -- ud4 = ud3;
  -- 
  -- ud3 = ud2;
  -- 
  -- ud2 = ud1;
  -- 
  -- ud1 = x_in;
  u_dwt : dwt
    PORT MAP( x_in => x_in,  -- sfix14_En12 [8]
              tmp => tmp  -- sfix14_En12 [8]
              );

  y_out <= tmp;

END rtl;

